global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'nestjs'
  metrics_path: /metrics
  static_configs:
  - targets: [ 'nestjs:8001' ]

- job_name: 'elasticsearch'
  metrics_path: /
  static_configs:
  - targets: [ 'elasticsearch:9200' ]

  - job_name: 'elasticsearch-exporter'
    static_configs:
    - targets: [ 'elasticsearch-exporter:9114' ]
