global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'nestjs-app'
  static_configs:
  - targets: [ 'nestjs:8001' ]

- job_name: 'elasticsearch-exporter'
  static_configs:
  - targets: [ 'elasticsearch-exporter:9114' ]
